<!-- Optional; Here the user could browse between suggested/random items ->
<?php include "header.phtml" ?>
<?php include "menu.phtml"?>
<!------------------------------>
<!-- PC , USB, MOTHERBOARD, GRAPHICS CARD, ACCESSORIES-->
<div class="sideBar" >
    <form>
        <h1>Filter</h1>
        <input type="radio" name="stock" value="all"><label>&nbsp;All</label><br>
        <input type="radio" name="stock" value="inStock"><label>&nbsp;In-Stock-only</label><br>
        <input type="radio" name="stock" value="outStock"><label>&nbsp;Out of Stock</label><br><br><br><br>
        <input type="checkbox" name="pc" value="PC"><label>&nbsp;PC</label><br/>
        <input type="checkbox" name="motherboard" value="motherboard"><label>&nbsp;Mother Board</label><br/>
        <input type="checkbox" name="gc" value="gc"><label>&nbsp;Graphics Card</label><br/>
        <input type="checkbox" name="acc" value="acc"><label>&nbsp;Accessories</label><br/>
    </form>
</div>
<div class="ProductsTable">
    <h1>Available Products</h1>
</div>
<!------------------------------>
<?php include "footer.phtml" ?>
