<!-- Optional; Here the user could browse between suggested/random items ->
<?php include "header.phtml" ?>
<?php include "menu.phtml"?>
<!------------------------------>
<!-- PC , USB, MOTHERBOARD, GRAPHICS CARD, ACCESSORIES-->
<div id="sideBar" >
    <form>
        <h1>Filter</h1>
        <input type="radio" name="stock" value="all"><label>&nbsp;All</label><br>
        <input type="radio" name="stock" value="inStock"><label>&nbsp;In-Stock-only</label><br>
        <input type="radio" name="stock" value="outStock"><label>&nbsp;Out of Stock</label><br><br><br><br>
        <input type="checkbox" name="pc" value="PC"><label>&nbsp;PC</label><br/>
        <input type="checkbox" name="motherboard" value="motherboard"><label>&nbsp;Mother Board</label><br/>
        <input type="checkbox" name="gc" value="gc"><label>&nbsp;Graphics Card</label><br/>
        <input type="checkbox" name="acc" value="acc"><label>&nbsp;Accessories</label><br/>
    </form>
</div>
<div id="ProductsTable">
    <h1>Available Products</h1>
    <table id="product" class="with-currency" lang="en-NZ">
        <tr>
            <th>SKU</th>
            <th>Name</th>
            <th>Category</th>
            <th>Cost</th>
            <th>Stock Qty</th>
        </tr>
        <tbody id="products">
        <?
            foreach($products as $product ){
                $cost = $product->getCost() / 100;
                echo "
                    <tr>
                        <td>{$product->getStockKeepingUnit()}</td>
                        <td>{$product->getName()}</td>
                        <td>{$product->getCategory()->getName()}</td>
                        <td>{$cost}</td>
                        <td>{$product->getQuantity()}</td>
                    </tr>
                ";
            }
        ?>
        </tbody>
    </table>
</div>
<!------------------------------>
<?php include "footer.phtml" ?>
