<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <title>JIS TECH</title>
	    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
        <link rel="shortcut icon" href="/static/icons/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/static/icons/favicon.ico" type="image/x-icon">
        <!--Load all scripts-->
        <script src="/static/scripts/signUp.js" ></script>
	</head>
	<body>
        <img src="/static/icons/logo.png" alt="logo">
        <h1>Welcome</h1>
        <div id="page-wrap">
<!---------- Header ends --------------->