<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <title>JIS TECH</title>
	    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
        <link rel="shortcut icon" href="/static/icons/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/static/icons/favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!--Load all scripts-->
        <script src="/static/scripts/signUp.js" ></script>
	</head>
	<body id="body">
    <a href="<?= $linkTo('showHome'); ?>"><img src="/static/icons/logo.png" alt="logo"></a>
        <h1>Welcome</h1>
        <div id="page-wrap">
<!---------- Header ends --------------->