<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <title>JIS TECH</title>
	    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
        <link rel="shortcut icon" href="/static/icons/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/static/icons/favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!--Load all scripts-->
        <script src="/static/scripts/signUp.js" ></script>
	</head>
	<body id="body">
        <div id="page-wrap">
            <div id="logo">
            <a href="<?= $linkTo('showHome'); ?>"><img src="/static/icons/logo.png" alt="logo"></a>
            <label>
            <?
            $date = date("i-h-s");
            echo date("l, jS \of F ");
            ?>
            </label>
            </div>
<!---------- Header ends --------------->