<!--This is the login page, user must enter username and password in order to login-->
<?php include "header.phtml" ?>

<div id="logIn">
    <form method="post" >
        <? echo "<p class='errorMessage'>$error</p>"?>
        <table>
            <tr>
                <td>User Name:</td>
                <td><input type="text" name="userName" value="<?= $userName ?>"></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><input type="password" name="userPassword" value="<?= $userPassword ?>"></td>
            </tr>
            <tr>
                <td class="center"><input type="submit" value="Login" name="validateLogin"></td>
                <td><input type="submit" value="Sign up" name="signUp"></td>
            </tr>
        </table>
    </form>
</div>
<?php include "footer.phtml" ?>

