<!--This is the login page, user must enter username and password in order to login-->
<?php include "header.phtml" ?>

<form style="text-align:center;padding-top:80px;" method="post" >

    <? echo "<p style='color:red;'>$error</p>"?>
    <div class="login">
        <table>
            <tr>
                <td>User Name:</td>
                <td><input type="text" name="userName" value="<?= $userName ?>"></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><input type="password" name="userPassword" value="<?= $userPassword ?>"></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="Login" name="validateLogin"></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="Sign up" name="signUp"></td>
            </tr>
        </table>
    </div>
</form>

<?php include "footer.phtml" ?>

