<?php
/**
 * Created by PhpStorm.
 * @Author Isaac Clancy
 * Date: 19/10/2018
 * Time: 11:48 AM
 */

foreach($products as $product) {
    $cost = $product->getCost() / 100;
    echo "
        <tr>
            <td>{$product->getStockKeepingUnit()}</td>
            <td>{$product->getName()}</td>
            <td>{$product->getCategory()->getName()}</td>
            <td>{$cost}</td>
            <td>{$product->getQuantity()}</td>
        </tr>
    ";
}
