<!-- This Screen allows the user to search for any available item -->

<?php include "header.phtml" ?>
<?php include "menu.phtml"?>
<script>
    window.onload = function () {
        searcher.searchByName("", function() {
            let productsTableBody = document.getElementsByClassName('productsTableBody')[0];
            sortTable(productsTableBody, currentIndex, -orders[currentIndex]);
        });
    };
</script>
<!------------------------------>
<div class="center">
    <form action="" class="small-margin">
        <label for="txt1">Search: </label>
        <span class="search">
            <span class="fa fa-search"></span>
            <input type="search" id="txt1" onkeyup="searcher.searchByName(this.value, function() {
                let productsTableBody = document.getElementsByClassName('productsTableBody')[0];
                sortTable(productsTableBody, currentIndex, -orders[currentIndex]);
            })">
        </span>
    </form>
    <?php include "productsTable.phtml" ?>
</div>
<!------------------------------>
<?php include "footer.phtml" ?>
