<!-- This Screen allows the user to search for any available item ->

<?php include "header.phtml" ?>
<?php include "menu.phtml"?>
<!------------------------------>
<div class = "margin_35pc">
    <br>
    <form action="">
        <label for="txt1">Search: </label>
        <span class="search">
            <span class="fa fa-search"></span>
            <input type="search" id="txt1" onkeyup="searcher.search(this.value)">
        </span>
    </form>
    <table class="ProductsTableForSearch">
        <thead>
            <tr>
                <th>SKU</th>
                <th>Name</th>
                <th>Category</th>
                <th>Cost</th>
                <th>Stock Qty</th>
            </tr>
        </thead>
        <?php
        for($i=0; $i < 4; $i++){
            echo("
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            ");
        }
        ?>
    </table>
    <p>Suggestions: <span id="txtHint"></span></p>
</div>
<br>
<a class="backButton" href="<?= $linkTo('Home'); ?>">Back</a>
<!------------------------------>
<?php include "footer.phtml" ?>
