<!-- This Screen allows the user to search for any available item ->

<?php include "header.phtml" ?>
<!------------------------------>

<p>Start typing and we'll suggest products for you!</p>

<form action="">
    Products: <input type="text" id="txt1" onkeyup="showHint(this.value)">
</form>

<p>Suggestions: <span id="txtHint"></span></p>

<script>
    function showHint(str) {
        let xhttp;
        if (str.length == 0) {
            document.getElementById("txtHint").innerHTML = "";
            return;
        }
        xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("txtHint").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "gethint.asp?q="+str, true);
        xhttp.send();
    }
</script>

<!------------------------------>
<?php include "footer.phtml" ?>
