<!--This page allows users to create a new user account. Users must enter a user name that's not been used and
    password twice which must be identical
-->
<?php include "header.phtml" ?>
<!------------------------------>
<div id="signUp">

    <h2>Please Enter Your Details</h2>

    <form class="center" method="post" action="">

            <? echo "<p class='errorMessage'>$error</p>"?>
            <br>
            <table>
                <tr>
                    <td>Name:</td>
                    <td><input type="text" name="name" value="<?= $name ?>" required></td>
                </tr>
                <tr>
                    <td id="nameErrorMessage"></td>
                </tr>
                <tr>
                    <td>User Name:</td>
                    <td><input type="text" name="userName" value="<?= $userName ?>" required></td>
                </tr>
                <tr>

                </tr>
                <tr>
                    <td>Email:</td>
                    <td><input id="emailInput" type="text" name="email" value="<?= $email ?>" onfocusout="checkEmailFormat()" required></td>
                </tr>
                <tr>
                    <td id="emailErrorMessage"></td>
                </tr>
                <tr>
                    <td>Password:</td>
                    <td><input type="password" name="userPassword" value="<?= $userPassword ?>" required></td>
                </tr>
                <tr>
                    <td id="passwordErrorMessage"></td>
                </tr>
                <tr>
                    <td>Re-Enter Password:</td>
                    <td><input type="password" name="userPassword2" value="<?= $userPassword2 ?>" required></td>
                </tr>
                <tr>
                    <td colspan="2" class="center"><input type="submit" value="Sign Up" name="signUp">
                        <input type="reset" value="Reset">
                    </td>
                </tr>

            </table>
    </form>
</div>
<!------------------------------>
<?php include "footer.phtml" ?>


